// Pokemon data for the companion app
import type { Synergy, Rarity, PokemonData } from "./types";

// Get sprite URL for a Pokemon
export function getPokemonSpriteUrl(index: string): string {
  return `https://raw.githubusercontent.com/keldaanCommunity/pokemonAutoChess/master/app/public/src/assets/avatar/${index}.png`;
}

// Get rarity color
export function getRarityColor(rarity: Rarity): string {
  switch (rarity) {
    case "COMMON":
      return "#9CA3AF";
    case "UNCOMMON":
      return "#22C55E";
    case "RARE":
      return "#3B82F6";
    case "EPIC":
      return "#A855F7";
    case "UNIQUE":
      return "#F59E0B";
    case "LEGENDARY":
      return "#EF4444";
    default:
      return "#9CA3AF";
  }
}

// Sample Pokemon list - in production this would be fetched from the game data
export const PokemonList: PokemonData[] = [
  {
    index: "0001",
    name: "BULBASAUR",
    types: ["GRASS", "POISON", "FLORA"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 1,
    hp: 90,
    atk: 5,
    def: 2,
    speDef: 2,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "VINE_WHIP",
  },
  {
    index: "0002",
    name: "IVYSAUR",
    types: ["GRASS", "POISON", "FLORA"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 2,
    hp: 180,
    atk: 10,
    def: 4,
    speDef: 4,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "VINE_WHIP",
  },
  {
    index: "0003",
    name: "VENUSAUR",
    types: ["GRASS", "POISON", "FLORA"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 3,
    hp: 360,
    atk: 20,
    def: 8,
    speDef: 8,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "PETAL_DANCE",
  },
  {
    index: "0004",
    name: "CHARMANDER",
    types: ["FIRE", "DRAGON"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 1,
    hp: 80,
    atk: 6,
    def: 2,
    speDef: 2,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "FIRE_SPIN",
  },
  {
    index: "0005",
    name: "CHARMELEON",
    types: ["FIRE", "DRAGON"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 2,
    hp: 160,
    atk: 12,
    def: 4,
    speDef: 4,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "FIRE_SPIN",
  },
  {
    index: "0006",
    name: "CHARIZARD",
    types: ["FIRE", "DRAGON", "FLYING"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 3,
    hp: 320,
    atk: 24,
    def: 8,
    speDef: 8,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "BLAST_BURN",
  },
  {
    index: "0007",
    name: "SQUIRTLE",
    types: ["WATER", "AQUATIC"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 1,
    hp: 85,
    atk: 5,
    def: 3,
    speDef: 2,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "WATER_GUN",
  },
  {
    index: "0008",
    name: "WARTORTLE",
    types: ["WATER", "AQUATIC"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 2,
    hp: 170,
    atk: 10,
    def: 6,
    speDef: 4,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "WATER_GUN",
  },
  {
    index: "0009",
    name: "BLASTOISE",
    types: ["WATER", "AQUATIC"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 3,
    hp: 340,
    atk: 20,
    def: 12,
    speDef: 8,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "HYDRO_CANNON",
  },
  {
    index: "0025",
    name: "PIKACHU",
    types: ["ELECTRIC", "FAIRY"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 1,
    hp: 70,
    atk: 7,
    def: 1,
    speDef: 1,
    speed: 2,
    range: 1,
    pp: 80,
    skill: "THUNDERBOLT",
  },
  {
    index: "0026",
    name: "RAICHU",
    types: ["ELECTRIC", "FAIRY"] as Synergy[],
    rarity: "UNCOMMON",
    stars: 2,
    hp: 140,
    atk: 14,
    def: 2,
    speDef: 2,
    speed: 2,
    range: 1,
    pp: 80,
    skill: "THUNDER",
  },
  {
    index: "0133",
    name: "EEVEE",
    types: ["NORMAL", "FIELD"] as Synergy[],
    rarity: "COMMON",
    stars: 1,
    hp: 60,
    atk: 5,
    def: 2,
    speDef: 2,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "TACKLE",
  },
  {
    index: "0150",
    name: "MEWTWO",
    types: ["PSYCHIC", "ARTIFICIAL"] as Synergy[],
    rarity: "LEGENDARY",
    stars: 3,
    hp: 400,
    atk: 30,
    def: 5,
    speDef: 10,
    speed: 2,
    range: 3,
    pp: 100,
    skill: "PSYSTRIKE",
  },
  {
    index: "0151",
    name: "MEW",
    types: ["PSYCHIC", "FAIRY"] as Synergy[],
    rarity: "UNIQUE",
    stars: 2,
    hp: 200,
    atk: 15,
    def: 5,
    speDef: 5,
    speed: 2,
    range: 2,
    pp: 80,
    skill: "TRANSFORM",
  },
  {
    index: "0094",
    name: "GENGAR",
    types: ["GHOST", "POISON", "AMORPHOUS"] as Synergy[],
    rarity: "RARE",
    stars: 3,
    hp: 280,
    atk: 22,
    def: 4,
    speDef: 6,
    speed: 2,
    range: 1,
    pp: 100,
    skill: "SHADOW_BALL",
  },
  {
    index: "0149",
    name: "DRAGONITE",
    types: ["DRAGON", "FLYING"] as Synergy[],
    rarity: "EPIC",
    stars: 3,
    hp: 350,
    atk: 28,
    def: 6,
    speDef: 6,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "DRACO_METEOR",
  },
  {
    index: "0143",
    name: "SNORLAX",
    types: ["NORMAL", "MONSTER"] as Synergy[],
    rarity: "EPIC",
    stars: 3,
    hp: 500,
    atk: 20,
    def: 10,
    speDef: 8,
    speed: 0,
    range: 1,
    pp: 100,
    skill: "BODY_SLAM",
  },
  {
    index: "0131",
    name: "LAPRAS",
    types: ["WATER", "ICE", "AQUATIC"] as Synergy[],
    rarity: "RARE",
    stars: 2,
    hp: 250,
    atk: 12,
    def: 6,
    speDef: 8,
    speed: 1,
    range: 2,
    pp: 100,
    skill: "ICE_BEAM",
  },
  {
    index: "0248",
    name: "TYRANITAR",
    types: ["ROCK", "DARK", "MONSTER"] as Synergy[],
    rarity: "EPIC",
    stars: 3,
    hp: 400,
    atk: 26,
    def: 10,
    speDef: 6,
    speed: 1,
    range: 1,
    pp: 100,
    skill: "STONE_EDGE",
  },
  {
    index: "0445",
    name: "GARCHOMP",
    types: ["DRAGON", "GROUND"] as Synergy[],
    rarity: "EPIC",
    stars: 3,
    hp: 380,
    atk: 28,
    def: 8,
    speDef: 5,
    speed: 2,
    range: 1,
    pp: 100,
    skill: "EARTHQUAKE",
  },
];
